import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative } from 'node:path'

import { pc, RSP_DIR } from '../core/config.js'
import { parseFrontmatter, walkMarkdownFiles } from '../core/helpers.js'
import { withRspLock } from '../core/lock.js'

/**
 * Regenerate the .rsp/archives/INDEX.md file by scanning all archived
 * feature files and extracting date, name, and summary metadata.
 */
export async function buildArchiveIndex({ acquireLock = true } = {}) {
  if (acquireLock)
    return withRspLock('archive-index', async () => buildArchiveIndex({ acquireLock: false }))

  const archiveDir = join(RSP_DIR, 'archives')

  if (!existsSync(archiveDir)) {
    console.log(`  ${pc.dim('No archives directory.')}\n`)
    return
  }

  const archiveFiles = (await walkMarkdownFiles(archiveDir))
    .filter(fp => basename(fp) !== 'INDEX.md')
    .sort()

  const lines: string[] = []
  lines.push('# Archive Index')
  lines.push('')
  lines.push(`Generated: ${new Date().toISOString().slice(0, 10)}`)
  lines.push('')
  if (archiveFiles.length === 0) {
    lines.push('_No archived features yet._')
  }
  else {
    lines.push('| Date | Feature | Summary |')
    lines.push('|------|---------|---------|')
  }

  for (const fp of archiveFiles) {
    const base = basename(fp)
    const archiveRel = relative(archiveDir, fp)
    const archiveDirPart = dirname(archiveRel)

    const dateMatch = base.match(/^(\d{4}-\d{2}-\d{2})_(.+)\.md$/)
    const date = dateMatch ? dateMatch[1] : '—'
    const baseName = dateMatch ? dateMatch[2] : base.replace(/\.md$/, '')
    const featureName = archiveDirPart !== '.' ? `${archiveDirPart}/${baseName}` : baseName

    let summary = ''
    try {
      const content = await readFile(fp, 'utf-8')
      const fm = parseFrontmatter(content)
      if (fm?.summary)
        summary = String(fm.summary)
      if (!summary) {
        // eslint-disable-next-line regexp/no-super-linear-backtracking
        const specMatch = content.match(/^## Spec[\s\S]*?\n- Summary:[ \t]*([^\n]+)$/m)
        if (specMatch)
          summary = specMatch[1].trim()
      }
    }
    catch { /* ignore malformed archive entries */ }

    const summaryCell = summary ? summary.replace(/\|/g, '\\|') : '—'
    lines.push(`| ${date} | ${featureName} | ${summaryCell} |`)
  }

  lines.push('')
  lines.push('_Auto-generated by `rsp archive-index`._')

  const indexPath = join(archiveDir, 'INDEX.md')
  await writeFile(indexPath, lines.join('\n'))

  console.log(`  ${pc.green('INDEX.md updated:')} ${archiveFiles.length} archived feature(s).\n`)
}
