import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative } from 'node:path'

import { ARCHIVES_DIR, pc } from '../core/config.js'
import { extractSection, normalizeLogicalPath, walkMarkdownFiles } from '../core/helpers.js'
import { withRspLock } from '../core/lock.js'

/** Regenerate the .rsp/archives/INDEX.md file by scanning archived change files. */
export async function buildArchiveIndex({ acquireLock = true } = {}) {
  if (acquireLock)
    return withRspLock('archive-index', async () => buildArchiveIndex({ acquireLock: false }))

  if (!existsSync(ARCHIVES_DIR)) {
    console.log(`  ${pc.dim('No archives directory.')}\n`)
    return
  }

  const archiveFiles = (await walkMarkdownFiles(ARCHIVES_DIR))
    .filter(fp => basename(fp) !== 'INDEX.md')
    .sort()

  const lines: string[] = []
  lines.push('# Archive Index')
  lines.push('')
  lines.push(`Generated: ${new Date().toISOString().slice(0, 10)}`)
  lines.push('')
  if (archiveFiles.length === 0) {
    lines.push('_No archived changes yet._')
  }
  else {
    lines.push('| Date | Change | Summary |')
    lines.push('|------|--------|---------|')
  }

  for (const fp of archiveFiles) {
    const base = basename(fp)
    const archiveRel = normalizeLogicalPath(relative(ARCHIVES_DIR, fp))
    const archiveDirPart = dirname(archiveRel)

    const dateMatch = base.match(/^(\d{4}-\d{2}-\d{2})_(.+)\.md$/)
    const date = dateMatch ? dateMatch[1] : '—'
    const baseName = dateMatch ? dateMatch[2] : base.replace(/\.md$/, '')
    const changeName = archiveDirPart !== '.' ? `${archiveDirPart}/${baseName}` : baseName

    let summary = ''
    try {
      const content = await readFile(fp, 'utf-8')
      const proposal = extractSection(content, 'Proposal')
      const summaryLine = proposal
        .split('\n')
        .map(line => line.trim())
        .find(line => line.startsWith('- Summary:'))
      if (summaryLine)
        summary = summaryLine.slice('- Summary:'.length).trim()
    }
    catch { /* ignore malformed archive entries */ }

    const summaryCell = summary ? summary.replace(/\|/g, '\\|') : '—'
    lines.push(`| ${date} | ${changeName} | ${summaryCell} |`)
  }

  lines.push('')
  lines.push('_Auto-generated by `rsp update`._')

  const indexPath = join(ARCHIVES_DIR, 'INDEX.md')
  await writeFile(indexPath, lines.join('\n'))

  console.log(`  ${pc.green('INDEX.md updated:')} ${archiveFiles.length} archived change(s).\n`)
}
