import type { CommandRunOptions, RuntimeDiagnostic } from '../types.js'
import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { basename, join, relative } from 'node:path'

import { CHANGES_DIR, CONFIG_PATH, FOCUS_DIR, pc, RSP_DIR } from '../core/config.js'
import { changeNameFromPath, hasRspAgentsBlock, normalizeLogicalPath, parseYamlText, walkFiles, walkMarkdownFiles } from '../core/helpers.js'
import { emitJson, recordRuntimeDiagnostic, toErrorMessage } from '../core/output.js'

interface DoctorCheck {
  status: 'ok' | 'issue' | 'info'
  label: string
  message?: string
  hint?: string
}

interface DoctorResult {
  command: 'doctor'
  ok: boolean
  checks: DoctorCheck[]
  runtime: RuntimeDiagnostic[]
  summary: {
    issues: number
  }
}

export async function runDoctor(options: CommandRunOptions = {}): Promise<DoctorResult> {
  const checks: DoctorCheck[] = []
  const runtime: RuntimeDiagnostic[] = []
  const reportRuntime = (diagnostic: RuntimeDiagnostic) => recordRuntimeDiagnostic(runtime, diagnostic, Boolean(options.verbose) && !options.json)

  const rspRulesPath = join(RSP_DIR, 'rules', 'rsp-rules.md')
  const designPath = join(RSP_DIR, 'specs', 'design.md')
  const specsIndexPath = join(RSP_DIR, 'specs', 'INDEX.md')
  const archivesIndexPath = join(RSP_DIR, 'archives', 'INDEX.md')

  reportCheck(checks, '.rsp exists', existsSync(RSP_DIR), 'Run: rsp init')
  reportCheck(checks, 'rules/rsp-rules.md exists', existsSync(rspRulesPath), 'Run: rsp init')
  reportCheck(checks, 'specs/design.md exists', existsSync(designPath), 'Run: rsp init')
  reportCheck(checks, 'specs/INDEX.md exists', existsSync(specsIndexPath), 'Run: rsp update')
  reportCheck(checks, 'archives/INDEX.md exists', existsSync(archivesIndexPath), 'Run: rsp update')

  await checkAgents(checks, reportRuntime)
  await checkGeneratedIndex(checks, reportRuntime, specsIndexPath, '_Auto-generated by `rsp update`._', 'specs/INDEX.md has generated signature', 'Run: rsp update')
  await checkGeneratedIndex(checks, reportRuntime, archivesIndexPath, '_Auto-generated by `rsp update`._', 'archives/INDEX.md has generated signature', 'Run: rsp update')
  await checkArchiveNaming(checks, reportRuntime)
  await checkConfigSemantics(checks, reportRuntime)
  await checkActiveChangeConsistency(checks, reportRuntime)

  const result: DoctorResult = {
    command: 'doctor',
    ok: checks.every(check => check.status !== 'issue'),
    checks,
    runtime,
    summary: {
      issues: checks.filter(check => check.status === 'issue').length,
    },
  }

  if (options.json) {
    emitJson(result)
    return result
  }

  console.log()
  console.log(`  ${pc.bold('RSP doctor')}`)
  console.log()
  for (const check of checks)
    printDoctorCheck(check)

  if (result.summary.issues === 0)
    console.log(`\n  ${pc.green('✓')} RSP setup looks healthy.\n`)
  else
    console.log(`\n  ${pc.yellow(String(result.summary.issues))} issue(s) detected.\n`)

  return result
}

function reportCheck(checks: DoctorCheck[], label: string, ok: boolean, fixHint?: string): void {
  if (ok) {
    checks.push({ status: 'ok', label })
    return
  }
  checks.push({ status: 'issue', label, hint: fixHint })
}

function printDoctorCheck(check: DoctorCheck): void {
  if (check.status === 'ok') {
    console.log(`  ${pc.green('✓')} ${check.label}`)
    return
  }
  if (check.status === 'info') {
    console.log(`  ${pc.dim(`Info: ${check.message || check.label}`)}`)
    if (check.hint)
      console.log(`    ${pc.dim(check.hint)}`)
    return
  }

  console.log(`  ${pc.yellow('!')} ${check.message || check.label}`)
  if (check.hint)
    console.log(`    ${pc.dim(check.hint)}`)
}

async function checkAgents(checks: DoctorCheck[], reportRuntime: (diagnostic: RuntimeDiagnostic) => void): Promise<void> {
  if (!existsSync('AGENTS.md')) {
    checks.push({ status: 'issue', label: 'AGENTS.md contains managed RSP block', message: 'AGENTS.md missing', hint: 'Run: rsp init' })
    return
  }

  let agents: string
  try {
    agents = await readFile('AGENTS.md', 'utf-8')
  }
  catch (error) {
    reportRuntime({
      code: 'agents_read_failed',
      operation: 'readFile',
      path: 'AGENTS.md',
      message: toErrorMessage(error),
    })
    checks.push({ status: 'issue', label: 'AGENTS.md contains managed RSP block', message: 'AGENTS.md could not be read', hint: 'Check AGENTS.md permissions or recreate it with rsp init' })
    return
  }

  if (hasRspAgentsBlock(agents)) {
    checks.push({ status: 'ok', label: 'AGENTS.md contains managed RSP block' })
    return
  }

  checks.push({ status: 'issue', label: 'AGENTS.md contains managed RSP block', message: 'AGENTS.md missing managed RSP block', hint: 'Run: rsp init' })
}

async function checkGeneratedIndex(checks: DoctorCheck[], reportRuntime: (diagnostic: RuntimeDiagnostic) => void, path: string, signature: string, label: string, fixHint: string): Promise<void> {
  if (!existsSync(path))
    return

  let content: string
  try {
    content = await readFile(path, 'utf-8')
  }
  catch (error) {
    reportRuntime({
      code: 'generated_index_read_failed',
      operation: 'readFile',
      path,
      message: toErrorMessage(error),
    })
    checks.push({ status: 'issue', label, message: `${label} could not be read`, hint: fixHint })
    return
  }

  if (content.includes(signature)) {
    checks.push({ status: 'ok', label })
    return
  }

  checks.push({ status: 'issue', label, hint: fixHint })
}

async function checkArchiveNaming(checks: DoctorCheck[], reportRuntime: (diagnostic: RuntimeDiagnostic) => void): Promise<void> {
  const archivesDir = join(RSP_DIR, 'archives')
  const archiveFiles = existsSync(archivesDir)
    ? (await walkMarkdownFiles(archivesDir, { onError: reportRuntime })).filter(fp => relative(archivesDir, fp) !== 'INDEX.md')
    : []

  const invalidFiles = archiveFiles
    .map(fp => normalizeLogicalPath(relative(archivesDir, fp)))
    .filter(fp => /^\d{4}-\d{2}-\d{2}_.+\.md$/.test(basename(fp)) === false)

  if (invalidFiles.length === 0) {
    checks.push({ status: 'ok', label: 'archived change files follow the date_name.md convention' })
    return
  }

  checks.push({
    status: 'issue',
    label: 'archived change files follow the date_name.md convention',
    message: `archived change files with invalid names: ${invalidFiles.join(', ')}`,
    hint: 'Rename archive files to YYYY-MM-DD_name.md and run: rsp update',
  })
}

async function checkConfigSemantics(checks: DoctorCheck[], reportRuntime: (diagnostic: RuntimeDiagnostic) => void): Promise<void> {
  if (!existsSync(CONFIG_PATH))
    return

  let content: string
  try {
    content = await readFile(CONFIG_PATH, 'utf-8')
  }
  catch (error) {
    reportRuntime({
      code: 'config_read_failed',
      operation: 'readFile',
      path: CONFIG_PATH,
      message: toErrorMessage(error),
    })
    checks.push({ status: 'issue', label: 'config.yaml semantic checks', message: 'config.yaml could not be read', hint: 'Check .rsp/config.yaml permissions or recreate it with rsp init' })
    return
  }

  let parsed: Record<string, unknown>
  try {
    parsed = parseYamlText(content)
  }
  catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    checks.push({ status: 'issue', label: 'config.yaml semantic checks', message: 'config.yaml is not valid YAML', hint: message })
    return
  }

  reportConfigListField(checks, parsed, 'kinds')

  if ('required_sections' in parsed) {
    checks.push({
      status: 'issue',
      label: 'config.yaml semantic checks',
      message: 'config.yaml field "required_sections" is no longer supported',
      hint: 'RSP keeps the core change section structure fixed. Remove "required_sections" from .rsp/config.yaml.',
    })
  }
}

function reportConfigListField(checks: DoctorCheck[], parsed: Record<string, unknown>, key: 'kinds'): void {
  if (!(key in parsed))
    return

  const value = parsed[key]
  if (!Array.isArray(value)) {
    checks.push({
      status: 'issue',
      label: 'config.yaml semantic checks',
      message: `config.yaml field "${key}" must be a YAML list`,
      hint: `Update .rsp/config.yaml so "${key}" is a YAML sequence (for example: ${key}: [item])`,
    })
    return
  }

  const items = value.map(String)
  const duplicates = [...new Set(items.filter((item, index) => items.indexOf(item) !== index))]
  if (duplicates.length === 0) {
    checks.push({ status: 'ok', label: `config.yaml field "${key}" has valid list semantics` })
    return
  }

  checks.push({
    status: 'issue',
    label: 'config.yaml semantic checks',
    message: `config.yaml field "${key}" contains duplicate entries: ${duplicates.join(', ')}`,
    hint: `Remove duplicate values from .rsp/config.yaml:${key}`,
  })
}

async function checkActiveChangeConsistency(checks: DoctorCheck[], reportRuntime: (diagnostic: RuntimeDiagnostic) => void): Promise<void> {
  const changeFiles = existsSync(CHANGES_DIR) ? await walkMarkdownFiles(CHANGES_DIR, { onError: reportRuntime }) : []
  const changeNames = new Set(changeFiles.map(fp => changeNameFromPath(CHANGES_DIR, fp)))

  const focusEntries = existsSync(FOCUS_DIR) ? await walkFiles(FOCUS_DIR, { onError: reportRuntime }) : []
  const focusNames = new Set(focusEntries.map(fp => normalizeLogicalPath(relative(FOCUS_DIR, fp))))

  const missingChangeFiles = [...focusNames].filter(name => !changeNames.has(name))
  const unfocusedChangeFiles = [...changeNames].filter(name => !focusNames.has(name))

  if (missingChangeFiles.length === 0) {
    checks.push({ status: 'ok', label: 'every focus marker maps to a change file' })
  }
  else {
    checks.push({
      status: 'issue',
      label: 'every focus marker maps to a change file',
      message: `focus markers without matching change files: ${missingChangeFiles.join(', ')}`,
      hint: 'Run: remove stale files in .rsp/focus.d/ or recreate the change with rsp create <name>',
    })
  }

  if (unfocusedChangeFiles.length === 0) {
    checks.push({ status: 'ok', label: 'focus markers are consistent with open changes' })
  }
  else {
    const preview = unfocusedChangeFiles.slice(0, 5).join(', ')
    const extra = unfocusedChangeFiles.length > 5 ? ` (+${unfocusedChangeFiles.length - 5} more)` : ''
    checks.push({
      status: 'info',
      label: 'focus markers are consistent with open changes',
      message: `unfocused open changes: ${preview}${extra}`,
      hint: 'Only changes listed in .rsp/focus.d/ are currently focused. Use rsp focus <name> to foreground one.',
    })
  }
}
