import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { join, relative } from 'node:path'

import { ACTIVE_DIR, CONFIG_PATH, pc, RSP_DIR } from '../core/config.js'
import { hasRspAgentsBlock, parseYamlLines, walkFiles, walkMarkdownFiles } from '../core/helpers.js'

export async function runDoctor(): Promise<number> {
  let issues = 0

  console.log()
  console.log(`  ${pc.bold('RSP doctor')}`)
  console.log()

  const rspRulesPath = join(RSP_DIR, 'rules', 'rsp-rules.md')
  const designPath = join(RSP_DIR, 'specs', 'design.md')
  const specsIndexPath = join(RSP_DIR, 'specs', 'INDEX.md')
  const archivesIndexPath = join(RSP_DIR, 'archives', 'INDEX.md')

  issues += reportCheck('.rsp exists', existsSync(RSP_DIR), 'Run: rsp init')
  issues += reportCheck('rules/rsp-rules.md exists', existsSync(rspRulesPath), 'Run: rsp init')
  issues += reportCheck('specs/design.md exists', existsSync(designPath), 'Run: rsp init')
  issues += reportCheck('specs/INDEX.md exists', existsSync(specsIndexPath), 'Run: rsp specs-index')
  issues += reportCheck('archives/INDEX.md exists', existsSync(archivesIndexPath), 'Run: rsp archive-index')

  issues += await checkAgents()
  issues += await checkGeneratedIndex(specsIndexPath, '_Auto-generated by `rsp specs-index`._', 'specs/INDEX.md has generated signature', 'Run: rsp specs-index')
  issues += await checkGeneratedIndex(archivesIndexPath, '_Auto-generated by `rsp archive-index`._', 'archives/INDEX.md has generated signature', 'Run: rsp archive-index')
  issues += await checkConfigSemantics()
  issues += await checkActiveFeatureConsistency()

  if (issues === 0)
    console.log(`\n  ${pc.green('✓')} RSP setup looks healthy.\n`)
  else
    console.log(`\n  ${pc.yellow(String(issues))} issue(s) detected.\n`)

  return issues
}

function reportCheck(label: string, ok: boolean, fixHint?: string): number {
  if (ok) {
    console.log(`  ${pc.green('✓')} ${label}`)
    return 0
  }
  console.log(`  ${pc.yellow('!')} ${label}`)
  if (fixHint)
    console.log(`    ${pc.dim(fixHint)}`)
  return 1
}

async function checkAgents(): Promise<number> {
  if (!existsSync('AGENTS.md')) {
    console.log(`  ${pc.yellow('!')} AGENTS.md missing`)
    console.log(`    ${pc.dim('Run: rsp init --agents-mode managed')}`)
    return 1
  }

  const agents = await readFile('AGENTS.md', 'utf-8')
  if (hasRspAgentsBlock(agents)) {
    console.log(`  ${pc.green('✓')} AGENTS.md contains managed RSP block`)
    return 0
  }

  console.log(`  ${pc.yellow('!')} AGENTS.md missing managed RSP block`)
  console.log(`    ${pc.dim('Run: rsp init --agents-mode managed')}`)
  return 1
}

async function checkGeneratedIndex(path: string, signature: string, label: string, fixHint: string): Promise<number> {
  if (!existsSync(path))
    return 0

  const content = await readFile(path, 'utf-8')
  if (content.includes(signature)) {
    console.log(`  ${pc.green('✓')} ${label}`)
    return 0
  }

  console.log(`  ${pc.yellow('!')} ${label}`)
  console.log(`    ${pc.dim(fixHint)}`)
  return 1
}

async function checkConfigSemantics(): Promise<number> {
  if (!existsSync(CONFIG_PATH))
    return 0

  const content = await readFile(CONFIG_PATH, 'utf-8')
  const parsed = parseYamlLines(content.split('\n'))
  let issues = 0

  issues += reportConfigListField(parsed, 'statuses')
  issues += reportConfigListField(parsed, 'priorities')
  issues += reportConfigListField(parsed, 'required_sections')

  return issues
}

function reportConfigListField(parsed: Record<string, unknown>, key: 'statuses' | 'priorities' | 'required_sections'): number {
  if (!(key in parsed))
    return 0

  const value = parsed[key]
  if (!Array.isArray(value)) {
    console.log(`  ${pc.yellow('!')} config.yaml field "${key}" must be a YAML list`)
    console.log(`    ${pc.dim(`Update .rsp/config.yaml so "${key}" uses "key:" followed by indented "- item" entries`)}`)
    return 1
  }

  const items = value.map(String)
  const duplicates = [...new Set(items.filter((item, index) => items.indexOf(item) !== index))]
  if (duplicates.length === 0) {
    console.log(`  ${pc.green('✓')} config.yaml field "${key}" has valid list semantics`)
    return 0
  }

  console.log(`  ${pc.yellow('!')} config.yaml field "${key}" contains duplicate entries: ${duplicates.join(', ')}`)
  console.log(`    ${pc.dim(`Remove duplicate values from .rsp/config.yaml:${key}`)}`)
  return 1
}

async function checkActiveFeatureConsistency(): Promise<number> {
  const featuresDir = join(RSP_DIR, 'features')
  const featureFiles = existsSync(featuresDir) ? await walkMarkdownFiles(featuresDir) : []
  const featureNames = new Set(featureFiles.map(fp => relative(featuresDir, fp).replace(/\.md$/, '')))

  const activeEntries = existsSync(ACTIVE_DIR) ? await walkFiles(ACTIVE_DIR) : []
  const activeNames = new Set(activeEntries.map(fp => relative(ACTIVE_DIR, fp)))

  const missingFeatureFiles = [...activeNames].filter(name => !featureNames.has(name))
  const unstagedActiveMarkers = [...featureNames].filter(name => !activeNames.has(name))

  let issues = 0
  if (missingFeatureFiles.length === 0) {
    console.log(`  ${pc.green('✓')} every active marker maps to a feature file`)
  }
  else {
    console.log(`  ${pc.yellow('!')} active markers without matching feature files: ${missingFeatureFiles.join(', ')}`)
    console.log(`    ${pc.dim('Run: remove stale files in .rsp/active.d/ or recreate the feature with rsp new <name>')}`)
    issues++
  }

  if (unstagedActiveMarkers.length === 0) {
    console.log(`  ${pc.green('✓')} every feature file has an active marker`)
  }
  else {
    console.log(`  ${pc.yellow('!')} feature files without active markers: ${unstagedActiveMarkers.join(', ')}`)
    console.log(`    ${pc.dim('Run: recreate the marker with rsp new <name> or archive the feature with rsp close <name>')}`)
    issues++
  }

  return issues
}
