import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { join, relative } from 'node:path'

import { ACTIVE_DIR, pc, RSP_DIR } from '../core/config.js'
import { hasRspAgentsBlock, walkFiles, walkMarkdownFiles } from '../core/helpers.js'

export async function runDoctor(): Promise<number> {
  let issues = 0

  console.log()
  console.log(`  ${pc.bold('RSP doctor')}`)
  console.log()

  const rspRulesPath = join(RSP_DIR, 'rules', 'rsp-rules.md')
  const designPath = join(RSP_DIR, 'specs', 'design.md')
  const specsIndexPath = join(RSP_DIR, 'specs', 'INDEX.md')
  const archivesIndexPath = join(RSP_DIR, 'archives', 'INDEX.md')

  issues += reportCheck('.rsp exists', existsSync(RSP_DIR))
  issues += reportCheck('rules/rsp-rules.md exists', existsSync(rspRulesPath))
  issues += reportCheck('specs/design.md exists', existsSync(designPath))
  issues += reportCheck('specs/INDEX.md exists', existsSync(specsIndexPath))
  issues += reportCheck('archives/INDEX.md exists', existsSync(archivesIndexPath))

  issues += await checkAgents()
  issues += await checkGeneratedIndex(specsIndexPath, '_Auto-generated by `rsp specs-index`._', 'specs/INDEX.md has generated signature')
  issues += await checkGeneratedIndex(archivesIndexPath, '_Auto-generated by `rsp archive-index`._', 'archives/INDEX.md has generated signature')
  issues += await checkActiveFeatureConsistency()

  if (issues === 0)
    console.log(`\n  ${pc.green('✓')} RSP setup looks healthy.\n`)
  else
    console.log(`\n  ${pc.yellow(String(issues))} issue(s) detected.\n`)

  return issues
}

function reportCheck(label: string, ok: boolean): number {
  if (ok) {
    console.log(`  ${pc.green('✓')} ${label}`)
    return 0
  }
  console.log(`  ${pc.yellow('!')} ${label}`)
  return 1
}

async function checkAgents(): Promise<number> {
  if (!existsSync('AGENTS.md')) {
    console.log(`  ${pc.yellow('!')} AGENTS.md missing`)
    return 1
  }

  const agents = await readFile('AGENTS.md', 'utf-8')
  if (hasRspAgentsBlock(agents)) {
    console.log(`  ${pc.green('✓')} AGENTS.md contains managed RSP block`)
    return 0
  }

  console.log(`  ${pc.yellow('!')} AGENTS.md missing managed RSP block`)
  return 1
}

async function checkGeneratedIndex(path: string, signature: string, label: string): Promise<number> {
  if (!existsSync(path))
    return 0

  const content = await readFile(path, 'utf-8')
  if (content.includes(signature)) {
    console.log(`  ${pc.green('✓')} ${label}`)
    return 0
  }

  console.log(`  ${pc.yellow('!')} ${label}`)
  return 1
}

async function checkActiveFeatureConsistency(): Promise<number> {
  const featuresDir = join(RSP_DIR, 'features')
  const featureFiles = existsSync(featuresDir) ? await walkMarkdownFiles(featuresDir) : []
  const featureNames = new Set(featureFiles.map(fp => relative(featuresDir, fp).replace(/\.md$/, '')))

  const activeEntries = existsSync(ACTIVE_DIR) ? await walkFiles(ACTIVE_DIR) : []
  const activeNames = new Set(activeEntries.map(fp => relative(ACTIVE_DIR, fp)))

  const missingFeatureFiles = [...activeNames].filter(name => !featureNames.has(name))
  const unstagedActiveMarkers = [...featureNames].filter(name => !activeNames.has(name))

  let issues = 0
  if (missingFeatureFiles.length === 0) {
    console.log(`  ${pc.green('✓')} every active marker maps to a feature file`)
  }
  else {
    console.log(`  ${pc.yellow('!')} active markers without matching feature files: ${missingFeatureFiles.join(', ')}`)
    issues++
  }

  if (unstagedActiveMarkers.length === 0) {
    console.log(`  ${pc.green('✓')} every feature file has an active marker`)
  }
  else {
    console.log(`  ${pc.yellow('!')} feature files without active markers: ${unstagedActiveMarkers.join(', ')}`)
    issues++
  }

  return issues
}
