import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { basename, join, relative } from 'node:path'

import { pc, RSP_DIR } from '../core/config.js'
import { normalizeLogicalPath, parseFrontmatter, walkMarkdownFiles } from '../core/helpers.js'
import { withRspLock } from '../core/lock.js'

/** Regenerate the .rsp/specs/INDEX.md file as an index of additional project specs. */
export async function buildSpecsIndex({ acquireLock = true } = {}) {
  if (acquireLock)
    return withRspLock('specs-index', async () => buildSpecsIndex({ acquireLock: false }))

  const specsDir = join(RSP_DIR, 'specs')

  if (!existsSync(specsDir)) {
    console.log(`  ${pc.dim('No specs directory.')}\n`)
    return
  }

  const specFiles = (await walkMarkdownFiles(specsDir))
    .filter((fp) => {
      const name = basename(fp)
      return name !== 'INDEX.md' && name !== 'design.md'
    })
    .sort()

  const lines: string[] = []
  lines.push('# Specs Index')
  lines.push('')
  lines.push('_Additional project-level specs beyond `design.md`._')
  lines.push('')

  if (specFiles.length === 0) {
    lines.push('_No additional project-level specs yet._')
  }
  else {
    lines.push('| File | Title | Summary |')
    lines.push('|------|-------|---------|')

    for (const fp of specFiles) {
      const rel = normalizeLogicalPath(relative(specsDir, fp))
      const content = await readFile(fp, 'utf-8')
      const fm = parseFrontmatter(content)
      const fmTitle = fm && typeof fm.title === 'string' ? fm.title : ''
      const title = fmTitle || extractTitle(content) || rel.replace(/\.md$/, '')
      const summary = extractSummary(content, fm?.summary)
      lines.push(`| ${escapeCell(rel)} | ${escapeCell(title)} | ${escapeCell(summary || '—')} |`)
    }
  }

  lines.push('')
  lines.push('_Auto-generated by `rsp update`._')

  await writeFile(join(specsDir, 'INDEX.md'), lines.join('\n'))
  console.log(`  ${pc.green('INDEX.md updated:')} ${specFiles.length} spec file(s).\n`)
}

function extractTitle(content: string): string {
  for (const rawLine of content.split('\n')) {
    if (!rawLine.startsWith('# '))
      continue
    return rawLine.slice(2).trim()
  }
  return ''
}

function extractSummary(content: string, frontmatterSummary?: unknown): string {
  if (typeof frontmatterSummary === 'string' && frontmatterSummary.trim() !== '')
    return frontmatterSummary.trim()

  const lines = content.split('\n')
  let inFrontmatter = false

  for (const rawLine of lines) {
    const line = rawLine.trim()

    if (line === '---' || line === '...') {
      inFrontmatter = !inFrontmatter
      continue
    }
    if (inFrontmatter || line === '')
      continue
    if (line.startsWith('#'))
      continue
    if (line.startsWith('##'))
      continue

    return line.replace(/^[-*]\s*/, '').trim()
  }

  return ''
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|')
}
